#!/usr/bin/env python3

"""
build elmxx library
"""
import sys, os

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")

_LIBDIR = os.path.join(_CIMEROOT, "scripts", "Tools")
sys.path.append(_LIBDIR)

from standard_script_setup import *
from CIME.buildlib         import parse_input
from CIME.case             import Case
from CIME.utils            import expect, run_bld_cmd_ensure_logging

logger = logging.getLogger(__name__)

###############################################################################
def buildlib(bldroot, installpath, case):
###############################################################################
    casebuild = case.get_value("CASEBUILD")
    caseroot  = case.get_value("CASEROOT")
    srcroot   = case.get_value("SRCROOT")

    #-------------------------------------------------------
    # create Filepath in bldroot; unlike most other components,
    # elmxx makes its Filepath right here.
    #-------------------------------------------------------

    #-------------------------------------------------------
    # The ELMxx Kokkos/C++ library lives in a git submodule. Its Fortran
    # bindings (elmxx_mod.F90, ELMxxKokkos.F90) are compiled as part of the
    # library by components/cmake/build_model.cmake, not listed here -- adding
    # them to Filepath as well would compile them twice and produce duplicate
    # module files.
    #
    # Fail early and legibly if the submodule was never initialized, rather
    # than letting CMake fail later with a confusing missing-directory error.
    #-------------------------------------------------------
    elmxx_lib_dir = os.path.join(srcroot, "components", "elmxx",
                                 "external_models", "elmxx")
    expect(
        os.path.isfile(os.path.join(elmxx_lib_dir, "CMakeLists.txt")),
        "ELMxx C++ library not found at {}.\n"
        "Initialize the submodule:\n"
        "    cd {} && git submodule update --init --recursive "
        "components/elmxx/external_models/elmxx".format(elmxx_lib_dir, srcroot),
    )

    filepaths = \
 """{caseroot}/SourceMods/src.elmxx
{srcroot}/components/elmxx/src/main
{srcroot}/components/elmxx/src/cpl
""".format(caseroot=caseroot, srcroot=srcroot)

    with open(os.path.join(casebuild, "elmxxconf", "Filepath"), "w") as fd:
        fd.write(filepaths)

    with open(os.path.join(casebuild, "elmxxconf", "CIME_cppdefs"), "w") as fd:
        fd.write("")

###############################################################################
def _main_func():
###############################################################################
    caseroot, libroot, bldroot = parse_input(sys.argv)
    with Case(caseroot, read_only=False) as case:
        buildlib(bldroot, libroot, case)

###############################################################################

if __name__ == "__main__":
    _main_func()
